test:
  name: throughput-read-get-batch-by-id
  description: Throughput sweep for read transaction getBatchById
  workers:
    type: local
    number: 1
  rounds:
    - label: read-100
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-200
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-300
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-400
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-500
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-600
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 600
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-700
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-800
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 800
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-900
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 900
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
    - label: read-1000
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 0
