test:
  name: throughput-write-create-poultry-batch
  description: Throughput sweep for write transaction createPoultryBatch
  workers:
    type: local
    number: 4
  rounds:
    - label: write-50
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-100
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-150
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 150
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-200
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-250
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 250
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-300
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
