test:
  name: latency-critical-functions
  description: Average latency comparison for independent create functions
  workers:
    type: local
    number: 2
  rounds:
    - label: createFarmer
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createFarmer
    - label: createSlaughteringHouse
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createSlaughteringHouse
    - label: createRetailShop
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createRetailShop
    - label: createPoultryBatch
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createPoultryBatch
