test:
  name: latency-highload-functions
  description: High-load latency comparison for independent functions
  workers:
    type: local
    number: 4
  rounds:
    - label: createFarmer
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createFarmer
    - label: createSlaughteringHouse
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createSlaughteringHouse
    - label: createRetailShop
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createRetailShop
    - label: createPoultryBatch
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: createPoultryBatch
    - label: queryTraceOfBatch
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/latency-by-function.js
        arguments:
          contractId: halal_contract
          targetFunction: queryTraceOfBatch
          seedCount: 800
