test:
  name: throughput-read-get-batch-by-id
  description: Throughput sweep for read transaction getBatchById
  workers:
    type: local
    number: 4
  rounds:
    - label: read-500
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 500
    - label: read-1000
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 700
    - label: read-1500
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1500
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 900
    - label: read-2000
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 2000
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 1000
    - label: read-2500
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 2500
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 1200
    - label: read-3000
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 3000
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 1500
    - label: read-3500
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 3500
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 1700
    - label: read-4000
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 4000
      workload:
        module: workload/read-get-batch-by-id.js
        arguments:
          contractId: halal_contract
          seedCount: 2000
