test:
  name: throughput-write-create-poultry-batch
  description: Throughput sweep for write transaction createPoultryBatch
  workers:
    type: local
    number: 1
  rounds:
    - label: write-100
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-200
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-300
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-400
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-500
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-600
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 600
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-700
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-800
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 800
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-900
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 900
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
    - label: write-1000
      txDuration: 20
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: workload/write-create-poultry-batch.js
        arguments:
          contractId: halal_contract
