name: Fabric test-network for halal_contract benchmark
version: '2.0.0'
caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: halal_contract

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: User1
          clientPrivateKey:
            path: /home/hazzaz/workspace/hyperledger/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/62d770bcbfd63d36802a3fe926164144a28ddffd9a52ab60da3ca81b8745ae00_sk
          clientSignedCert:
            path: /home/hazzaz/workspace/hyperledger/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
    connectionProfile:
      path: /home/hazzaz/workspace/hyperledger/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
      discover: true
