'use strict';
const STATUS = {
    CREATED: 'CREATED',
    LIVE_TRANSPORTED: 'LIVE_TRANSPORTED',
    SLAUGHTERED: 'SLAUGHTERED',
    COLD_TRANSPORTED: 'COLD_TRANSPORTED',
    RETAILED: 'RETAILED'
};

const ALLOWED_TRANSITIONS = {
    CREATED: ['LIVE_TRANSPORTED'],
    LIVE_TRANSPORTED: ['SLAUGHTERED'],
    SLAUGHTERED: ['COLD_TRANSPORTED'],
    COLD_TRANSPORTED: ['RETAILED'],
    RETAILED: []
};

module.exports = { STATUS, ALLOWED_TRANSITIONS };
